name: parking_user_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  provider: ^6.1.1
  flutter_secure_storage: ^9.2.4
  http: ^1.1.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  intl: ^0.20.2
  geolocator: ^13.0.2
  font_awesome_flutter: ^10.8.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  country_code_picker: ^3.0.0
  webview_flutter: ^4.10.0
  qr_flutter: ^4.1.0
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.2
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  device_info_plus: ^10.1.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"
